### ISSUE TITLE
Webdeploy scripts failing to run on 2012 R2

### ISSUE THREAD

**Issue by justinmetz** [fti-technology/ringtail-deploy-service#26]
Noticed that the "Ringtail" webdeploy failed to run on a 2012 R2 test server.  Details from the Deployer.log file below.

Deployer............. 3/16/2016 11:48:29 AM
Read file: 8
About to deploy: C:\Program Files\FTI Technology\Ringtail\Ringtail.Web.Licensing_Package\Deploy.Ringtail.Web.Licensing.cmd
attempting to run deployment: C:\Program Files\FTI Technology\Ringtail\Ringtail.Web.Licensing_Package\Deploy.Ringtail.Web.Licensing.cmd
...reading from path: C:\Program Files\FTI Technology\Ringtail\Ringtail.Web.Licensing_Package
About to deploy: C:\Program Files\FTI Technology\Ringtail\RingtailSTS_Package\Deploy.Ringtail.STS.cmd
attempting to run deployment: C:\Program Files\FTI Technology\Ringtail\RingtailSTS_Package\Deploy.Ringtail.STS.cmd
...reading from path: C:\Program Files\FTI Technology\Ringtail\RingtailSTS_Package
About to deploy: C:\Program Files\FTI Technology\Ringtail\Ringtail.Web.UIStatic_Package\Deploy.Ringtail.UIStatic.cmd
attempting to run deployment: C:\Program Files\FTI Technology\Ringtail\Ringtail.Web.UIStatic_Package\Deploy.Ringtail.UIStatic.cmd
...reading from path: C:\Program Files\FTI Technology\Ringtail\Ringtail.Web.UIStatic_Package
About to deploy: C:\Program Files\FTI Technology\Ringtail\Ringtail.Web_Package\Deploy.Ringtail.cmd
attempting to run deployment: C:\Program Files\FTI Technology\Ringtail\Ringtail.Web_Package\Deploy.Ringtail.cmd
Process could not be started...
Object reference not set to an instance of an object.
   at Deployer.App.RegistryReaderScrubber.GetPathForRegKey(String key, String value)
   at Deployer.App.RegistryReaderScrubber.EndToEnd(String fileName, String outFile)
   at Deployer.App.DeploymentRunner.RunDeployment(String file, List`1 myBatch)
About to deploy: C:\Program Files\FTI Technology\Ringtail\Ringtail.WebServices_Package\Deploy.Ringtail.WebServices.cmd
attempting to run deployment: C:\Program Files\FTI Technology\Ringtail\Ringtail.WebServices_Package\Deploy.Ringtail.WebServices.cmd
...reading from path: C:\Program Files\FTI Technology\Ringtail\Ringtail.WebServices_Package
About to deploy: C:\Program Files\FTI Technology\Ringtail\Ringtail.Legal.Web_Package\Deploy.Ringtail.Web.cmd
attempting to run deployment: C:\Program Files\FTI Technology\Ringtail\Ringtail.Legal.Web_Package\Deploy.Ringtail.Web.cmd
...reading from path: C:\Program Files\FTI Technology\Ringtail\Ringtail.Legal.Web_Package
About to deploy: C:\Program Files\FTI Technology\Ringtail Processing Framework\Deployment Packages\RPF Coordinator Package\Deploy.Ringtail.ProcessFramework.Coordinator.cmd
attempting to run deployment: C:\Program Files\FTI Technology\Ringtail Processing Framework\Deployment Packages\RPF Coordinator Package\Deploy.Ringtail.ProcessFramework.Coordinator.cmd
...reading from path: C:\Program Files\FTI Technology\Ringtail Processing Framework\Deployment Packages\RPF Coordinator Package
About to deploy: C:\Program Files\FTI Technology\Ringtail Help\Ringtail.Help_Package\Deploy.Ringtail.Help.cmd
attempting to run deployment: C:\Program Files\FTI Technology\Ringtail Help\Ringtail.Help_Package\Deploy.Ringtail.Help.cmd
...reading from path: C:\Program Files\FTI Technology\Ringtail Help\Ringtail.Help_Package

**Comment by jakebrown58** [comment]
Fixed.
